import "typings-global";
export import beautylog = require("beautylog");
export let commander = require("commander");
export let gulp = require("gulp");
export let path = require("path");
export let q = require("q");
export let request = require("request");
export let shelljs = require("shelljs");
export let smartssh = require("smartssh");
export import smartstring = require("smartstring");
export import smartfile = require("smartfile");